### ISSUE TITLE
Timing out

### ISSUE THREAD

**Issue by gtkpr** [bashi/kombu#1]
For some reason it began timing out starting last night. It first displays the message, "Converting... It may take several minutes when you convert a large font." Eventually it times out and displays the error message "Worker time out."

This may obviously be a server issue, but I thought I'd bring it to your attention nonetheless. That is, if anyone still monitors this project page.

**Comment by bashi** [comment]
Sorry for the late response. Is it possible to provide the font you tried to convert? Looks like this is a bug in the app. This app doesn't communicate with servers while converting a font.

**Comment by gtkpr** [comment]
> Sorry for the late response. Is it possible to provide the font you tried to convert? Looks like this is a bug in the app. This app doesn't communicate with servers while converting a font.

For some reason it's happened with all of my font files that I've been trying to convert recently, so I haven't even tried any more as of recently :/ However, I just tested another one, and same issue. If you provide me with your email address, I'll send it over. Or can I just reply to the email notification that Github sent me?

**Comment by bashi** [comment]
My email address is in [package.json](https://github.com/bashi/kombu/blob/master/package.json#L22). Could you also tell me which browser you used?

**Comment by gtkpr** [comment]
> My email address is in [package.json](https://github.com/bashi/kombu/blob/master/package.json#L22). Could you also tell me which browser you used?

k i just sent you an email. im AJ

**Comment by bashi** [comment]
I think I configured a third-party library wrongly. I pushed a new config. Could you visit https://kombu.kanejaku.org/ and do a force reload (Shift + F5), then try to convert a font? Let me know if it still doesn't work.

**Comment by gtkpr** [comment]
> I think I configured a third-party library wrongly. I pushed a new config. Could you visit https://kombu.kanejaku.org/ and do a force reload (Shift + F5), then try to convert a font? Let me know if it still doesn't work.

ok, its working now. but now its forcing me to give all the files a name instead of simply assuming the old filename with the new file extension??

**Comment by bashi** [comment]
Thank you for the feedback. As of 0.1.5 I started using a new API that allows us to use native file chooser but it doesn't support default name for saving files yet (https://github.com/WICG/native-file-system/issues/80).

Probably better to revert the change and I'll work on this when I have time. For now can use Firefox/Safari/Edge to work around the problem. These browser don't support Native File System API. Currently Chrome is the only browser which supports the API.

**Comment by bashi** [comment]
Fix is up. Please let me know if something goes wrong. you may need another force reload.

**Comment by gtkpr** [comment]
> Fix is up. Please let me know if something goes wrong. you may need another force reload.

Beautiful. Everything is up and running as normal again.

What is the benefit of using the Native File System API over how you were doing it before?

**Comment by bashi** [comment]
Thank you for the confirmation. The API gives us more powerful control over files, e.g., selecting a folder to download. The main motivation was that I just wanted to try the API :)

**Comment by gtkpr** [comment]
> Thank you for the confirmation. The API gives us more powerful control over files, e.g., selecting a folder to download. The main motivation was that I just wanted to try the API :)

One last thing. I'm building an Electron app that uses file system. Do you mind pointing me to the documentation? Is [this](https://developer.mozilla.org/en-US/docs/Web/API/FileSystem) what you're talking about?

**Comment by bashi** [comment]
It seems related, but not really. I'm talking about https://web.dev/native-file-system/. These APIs are new and I'm not sure these are available on Electron yet.

**Comment by gtkpr** [comment]
> It seems related, but not really. I'm talking about https://web.dev/native-file-system/. These APIs are new and I'm not sure these are available on Electron yet.

Oh, yeah, damn it's really new eh. Thanks a bunch <3

**Comment by gtkpr** [comment]
hey, how do i use it to convert from, say, TTF to OTF or vice-versa?? it usually always only seems to convert to TTF.

**Comment by bashi** [comment]
Unfortunately converting 
 otf ↔ ttf isn't supported now. These are treated as the same internally. Could you file a new issue if you need the features?
