### ISSUE TITLE
JS Error: Worker time out

### ISSUE THREAD

**Issue by chennien** [bashi/kombu#5]
JS error occurred when try to convert a font file.

![Worker Timeout](https://user-images.githubusercontent.com/75157/147809025-020c75fd-9130-4f8b-a216-e238784e2558.png)

**Comment by bashi** [comment]
Which browser are you using? Can you share the name of your browser and the version? Looks like your browser doesn't support WebAssembly. This app requires WebAssembly support.

https://emscripten.org/docs/getting_started/FAQ.html#what-is-no-webassembly-support-found-build-with-s-wasm-0-to-target-javascript-instead-or-no-native-wasm-support-detected

**Comment by bashi** [comment]
Closing as this isn't actionable without further information.
