### ISSUE TITLE
Drop-Down fonts doesn't work. Woff2 to ttf not working

### ISSUE THREAD

**Issue by 0A7V9A** [bashi/kombu#6]
Drop-Down fonts doesn't work. Woff2 to ttf not working

**Comment by bashi** [comment]
Can you provide more information? Which browser do you use and what the version is? Can you check if there is error messages in DevTools (chrome, edge), Web Developer Tools (firefox), or Web Inspector (safari)? Also is the font available publicly?

**Comment by bashi** [comment]
Let me close this issue as there is no feedback.
